server:
  port: 8890
spring:
  application:
    name: 'admin'
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka1:8888/eureka/,http://eureka2:8886/eureka/'
    healthcheck:
      enabled: true
